language: cpp
dist: xenial

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
                        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
                  packages:
                      - clang-8
                      - libstdc++8
                      - cmake
          env:
              - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
              - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-7
                      - g++-7
                      - cmake
          env:
              - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - os: osx
          osx_image: xcode10.1

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - ./scripts/rebuild_all.sh
